<?php

namespace Tapestry\DesignBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\DesignBundle\Entity
 */
class TemplateRepository extends EntityRepository
{
}
