<?php

namespace Tapestry\CoreBundle\Entity\Core;

use Doctrine\ORM\EntityRepository;

/**
 * LimboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimboRepository extends EntityRepository
{
}
