<?php

namespace Tapestry\HostingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\HostingBundle\Entity
 */
class SiteRepository extends EntityRepository
{
}
