<?php

namespace Tapestry\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\ArticleBundle\Entity
 */
class ArticleRepository extends EntityRepository
{
}
