<?php

namespace Tapestry\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\ForumBundle\Entity
 */
class ThreadRepository extends EntityRepository
{
}
