<?php

namespace Tapestry\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\BlogBundle\Entity
 */
class BlogRepository extends EntityRepository
{
}
