<?php

namespace Tapestry\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class LimboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package Tapestry\CoreBundle\Entity
 */
class LimboRepository extends EntityRepository
{
}
